apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: shopping-demo
  name: fashion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-demo
      component: fashion
  template:
    metadata:
      labels:
        app: shopping-demo
        component: fashion
    spec:
      containers:
      - image: docker.io/mrbwilms/bestseller-fashion:latest
        name: fashion
        ports:
        - containerPort: 8082
        resources: {}
      restartPolicy: Always
