apiVersion: v1
kind: Service
metadata:
  namespace: shopping-demo
  name: fashion
spec:
  ports:
  - name: "http"
    port: 8082
    targetPort: 8082
  selector:
    app: shopping-demo
    component: fashion
