apiVersion: v1
kind: Service
metadata:
  namespace: shopping-demo
  name: toys
  labels:
    app: shopping-demo
    component: gateway
spec:
  ports:
  - name: "http"
    port: 8081
    targetPort: 8081
  selector:
    app: shopping-demo
    component: toys
