apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: shopping-demo
  name: hotdeals
  labels:
    app: shopping-demo
    component: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-demo
      component: hotdeals
  template:
    metadata:
      labels:
        app: shopping-demo
        component: hotdeals
    spec:
      containers:
      - image: docker.io/denniseffing/hot-deals:istio-demo
        imagePullPolicy: Always
        name: hotdeals
        ports:
        - containerPort: 8083
        resources: {}
      restartPolicy: Always
